In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import accuracy_score, mean_squared_error

In [16]:
df=pd.read_csv("C:/Users/PRINCE/OneDrive/Desktop/projects/diabetes.csv")

In [17]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [18]:
df.info

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   5

In [19]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [20]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [21]:
y=df['Outcome']

In [22]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [23]:
df.drop(columns=['Outcome'], axis=1, inplace=True)

In [24]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
linear=LinearRegression()

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(df, y, test_size=0.2, random_state=4)

In [29]:
linear.fit(X_train,Y_train)

LinearRegression()

In [30]:
Y_linear=linear.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
Y_linear

array([ 0.21084839,  0.08637561,  0.12213994,  0.3870521 ,  0.25041604,
        0.73822624,  0.52182944,  0.47225823,  0.89526726,  0.27046455,
        0.46534699,  0.01022673,  0.24744197,  0.00699211,  0.16345869,
        0.58858425,  0.82708643,  0.95752749, -0.04108241, -0.0225672 ,
        0.14689059,  0.65154637,  0.31825018,  0.76663686,  0.25900868,
        0.3264668 ,  0.12863406,  0.63457546,  0.30309412,  0.26140624,
        0.67790526,  0.00815309,  0.37055903, -0.01532183,  0.53349661,
        0.44202635,  0.62341375,  0.50133707,  0.17232266,  0.7533141 ,
        0.59018582,  0.35905118,  0.30172738,  0.6784094 ,  0.14741802,
        0.28552227,  0.35200029,  0.81498894,  0.28020722,  0.12311617,
        0.70555578,  0.62708192,  0.20718775,  0.56245371,  0.3442704 ,
        0.16405417,  0.36964027, -0.18757436,  0.1699033 ,  0.47705815,
        0.40570863,  0.13974016,  0.4058408 , -0.06017874,  0.2773426 ,
        0.34328677,  0.11675723,  0.49681023,  0.35506782,  0.54

In [33]:
Y_test

390    0
146    0
136    0
420    0
328    1
      ..
374    0
288    0
282    0
754    1
363    1
Name: Outcome, Length: 154, dtype: int64

In [34]:
Y_linear_final = np.round(Y_linear, decimals=0)

In [35]:
Y_linear_final

array([ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  1., -0., -0.,  0.,  1.,  0.,  1.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0.,  0., -0.,  1.,  0.,  1.,  1.,  0.,
        1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,
        0.,  1.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., -0.,  0.,  1.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  1.,  1.,  0., -0.,  1.,  0.,  0.,  1.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.])

In [36]:
accuracy_linear = accuracy_score(Y_test, Y_linear_final)

In [37]:
accuracy_linear

0.8051948051948052

In [38]:
from sklearn.linear_model import Lasso

In [39]:
lasso_model = Lasso(alpha=0.5)

In [40]:
lasso_model.fit(X_train, Y_train)

Lasso(alpha=0.5)

In [41]:
Y_lasso=lasso_model.predict(X_test)

In [42]:
Y_lasso

array([ 0.26113059,  0.02264199,  0.20225019,  0.39221552,  0.29114424,
        0.45983722,  0.61628842,  0.20054981,  0.58283462,  0.14979913,
        0.39175288,  0.14806162,  0.3020816 ,  0.09379277,  0.21460762,
        0.44852026,  0.75161322,  0.81277112,  0.12115358,  0.05322436,
        0.17798009,  0.52597437,  0.12464777,  0.62165816,  0.23371625,
        0.45761072,  0.09440276,  0.44006035,  0.40482647,  0.25944819,
        0.65123825,  0.08996876,  0.41102957,  0.02975713,  0.55267681,
        0.22452503,  0.44989647,  0.40353191,  0.13903405,  0.60294008,
        0.45581348,  0.3817305 ,  0.17679083,  0.72496242,  0.26109034,
        0.16202683,  0.19446853,  0.83506291,  0.22288959,  0.18194802,
        0.58386303,  0.65820698,  0.22662107,  0.38140141,  0.43295522,
        0.15244015,  0.24833514,  0.15316308,  0.26191647,  0.49011916,
        0.26666938,  0.1296517 ,  0.51899225, -0.10015231,  0.27941796,
        0.12798968,  0.04938113,  0.39279918,  0.36350023,  0.56

In [43]:
Y_lasso_final = np.round(Y_linear, decimals=0)

In [44]:
accuracy_lasso = accuracy_score(Y_test, Y_linear_final)

In [45]:
accuracy_lasso

0.8051948051948052

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [48]:
rf_classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [49]:
Y_rf = rf_classifier.predict(X_test)

In [50]:
accuracy_rf = accuracy_score(Y_test, Y_rf)

In [51]:
Y_rf

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1],
      dtype=int64)

In [52]:
accuracy_rf

0.7857142857142857